assignment: assignment5.md assignment5.bib Makefile
	pandoc assignment5.md \
	--output assignment5_Dunn.pdf \
	--smart \
	--bibliography=assignment5.bib \
	--csl=../../templates/ieee-with-url.csl \
	--template=../../templates/compact.latex \
	-V geometry:margin=1in

clean:
	rm assignment5.pdf