assignment: assignment4.md assignment4.bib Makefile
	pandoc assignment4.md \
	--output assignment4_Dunn.pdf \
	--smart \
	--bibliography=assignment4.bib \
	--csl=../../templates/ieee-with-url.csl \
	--template=../../templates/compact.latex \
	-V geometry:margin=1in

clean:
	rm assignment4.pdf