assignment: assignment8.md assignment8.bib Makefile
	pandoc assignment8.md \
	--output assignment8_Dunn.pdf \
	--smart \
	--bibliography=assignment8.bib \
	--csl=../../templates/ieee-with-url.csl \
	--template=../../templates/compact.latex \
	-V geometry:margin=1in

clean:
	rm assignment8.pdf