assignment: assignment6.md assignment6.bib Makefile
	pandoc assignment6.md \
	--output assignment6_Dunn.pdf \
	--smart \
	--bibliography=assignment6.bib \
	--csl=../../templates/ieee-with-url.csl \
	--template=../../templates/compact.latex \
	-V geometry:margin=1in

clean:
	rm assignment6.pdf