assignment: assignment7.md assignment7.bib Makefile
	pandoc assignment7.md \
	--output assignment7_Dunn.pdf \
	--smart \
	--bibliography=assignment7.bib \
	--csl=../../templates/ieee-with-url.csl \
	--template=../../templates/compact.latex \
	-V geometry:margin=1in

clean:
	rm assignment7.pdf